### ISSUE TITLE
testrail-report binary seems to have issues parsing TAP from file

### ISSUE THREAD

**Issue by troglodyne** [teodesian/TestRail-Perl#139]
Seeing lots of stack filled warns when trying to find a case, then it marks the result incorrectly:

    testrail-report --project Cobra --plan 'Integral Smoke - 68' --config 'CentOS 7 64-bit' --run CBCL tap_c7.out
    testrail-report
    ----------------------
    # Setting results...
    # Attempting to find case by title 'base-resetpass.cgi.pl_invitation.t in run 28742'...
    # Reporting result of case 44209031 in run 28742 as status '5'...# OK! (set to 5)
    Use of uninitialized value in concatenation (.) or string at /usr/local/cpanel/3rdparty/perl/524/lib64/perl5/cpanel_lib/Test/Rail/Parser.pm line 571.
    # Setting results...
    # Attempting to find case by title 'base-resetpass.cgi.pl_invitation.t line 67 in run 28742'...
    ERROR: Could not find test case: 0 at /usr/local/cpanel/3rdparty/perl/524/lib64/perl5/cpanel_lib/Test/Rail/Parser.pm line 634.
        Test::Rail::Parser::_set_result(Test::Rail::Parser=HASH(0x2e64fc8), 28742, "base-resetpass.cgi.pl_invitation.t line 67", 5, "    # submit_username called for marty\@r7ahl7nm.cptest at t/i"..., undef, undef) called at /usr/local/cpanel/3rdparty/perl/524/lib64/perl5/cpanel_lib/Test/Rail/Parser.pm line 603
        Test::Rail::Parser::EOFCallback(Test::Rail::Parser=HASH(0x2e64fc8)) called at /usr/local/cpanel/3rdparty/perl/524/lib64/perl5/5.24.1/TAP/Base.pm line 105
        TAP::Base::_make_callback(Test::Rail::Parser=HASH(0x2e64fc8), "EOF", Test::Rail::Parser=HASH(0x2e64fc8)) called at /usr/local/cpanel/3rdparty/perl/524/lib64/perl5/5.24.1/TAP/Parser.pm line 1450
        TAP::Parser::__ANON__() called at /usr/local/cpanel/3rdparty/perl/524/lib64/perl5/5.24.1/TAP/Parser.pm line 315
        TAP::Parser::next(Test::Rail::Parser=HASH(0x2e64fc8)) called at /usr/local/cpanel/3rdparty/perl/524/lib64/perl5/5.24.1/TAP/Parser.pm line 330
        TAP::Parser::run(Test::Rail::Parser=HASH(0x2e64fc8)) called at 3rdparty/perl/524/bin/testrail-report line 105
        TestRail::Bin::Report::run("args", ARRAY(0x13abb68)) called at 3rdparty/perl/524/bin/testrail-report line 16
    Use of uninitialized value in concatenation (.) or string at /usr/local/cpanel/3rdparty/perl/524/lib64/perl5/cpanel_lib/Test/Rail/Parser.pm line 571.
    # Setting results...
    # Attempting to find case by title 'base-resetpass.cgi.pl_invitation.t line 80 in run 28742'...

Example TAP from the test is attached
[tap.txt](https://github.com/teodesian/TestRail-Perl/files/1072293/tap.txt)

**Comment by teodesian** [comment]
Could not find test case: 0 means the call failed probably for a random reason like the server going down temporarily.  Should be mitigated with the retries stuff.
