### ISSUE TITLE
error uninitialized value in Parser.pm

### ISSUE THREAD

**Issue by TraceyC77** [teodesian/TestRail-Perl#143]
When running prove with the plugin

Use of uninitialized value in concatenation (.) or string at /usr/local/cpanel/3rdparty/perl/526/lib64/perl5/cpanel_lib/Test/Rail/Parser.pm line 571.

```

Test results were reported to TestRail (test naturally failed)

**Comment by teodesian** [comment]
This would be caused by a test doing done_testing(), but dying before calling it.  That would result in tests_planned being undefined when we emit the bad plan message.
