### ISSUE TITLE
Client doesn't retry after the seconds supplied in 'Retry-After' header on HTTP 429 (ratelimiting)

### ISSUE THREAD

**Issue by troglodyne** [teodesian/TestRail-Perl#144]
https://discuss.gurock.com/t/test-rail-api-http-429-too-many-requests/2029

We probably should be doing that instead of dying with "Too many connections"

**Comment by troglodyne** [comment]
Only caveats I'd say are worth watching for here are the following:
1. The seconds it supplies are way too long a wait, so there's no point in waiting that long
2. You retry and it defers you again -- how many retries do we do before giving up? Do we include the seconds in that threshhold when making the calculation of whether to continue retrying?

**Comment by teodesian** [comment]
The solution I have in place is to allow the user to specify a number of re-tries, and wait 5s between.  Does that sound like it's "good enough" for our purposes?

**Comment by troglodyne** [comment]
should work
