### ISSUE TITLE
No invalidation of cache in getSections

### ISSUE THREAD

**Issue by boris-papevis-aurea** [teodesian/TestRail-Perl#150]
Recurrent calls to getSections always return the same result.
The idea of caching is good, but only if the following is provided:
1. $suite_id is taken into account - as it's a function argument (there could be multiple suites per project - all yield the same cached result now).
2. There is an option to force reload.

I have used a simple workaround:
`$TestRail->{'sections'}->{$TestRailOpts->{'project'}} = undef;
my $sections = $TestRail->getSections( $TestRailOpts->{'project'}, $testRailActiveGroup{'suite'}->{'id'} );
`

**Comment by teodesian** [comment]
Cache invalidation is a systematic problem with this module.  I can try and pop the cache whenever we send requests to modify the relevant data though; that won't help if it's changing out from under you in a separate process, however.

I will look at this tomorrow, thank you for the report.

**Comment by teodesian** [comment]
OK, the problem is that I'm storing per project ID rather than per suite ID.

Easy enough, given suite ids are unique even across project.
