### ISSUE TITLE
No provision to run add_results_for_cases 

### ISSUE THREAD

**Issue by boris-papevis-aurea** [teodesian/TestRail-Perl#152]
Might have been analogous to bulkAddResults.
Workaround is to run 
`$TestRail->_doRequest("index.php?/api/v2/add_results_for_cases/$runid", 'POST', { 'results' => \@results })`
directly.

**Comment by teodesian** [comment]
Ahh, assigning by case ID rather than test ID.  OK, I'll add it.

**Comment by boris-papevis-aurea** [comment]
Thanks!
